flathub_packages_present:
  - name: ca.desrt.dconf-editor
  - name: com.google.Chrome
  - name: org.mozilla.firefox
  - name: org.mozilla.Thunderbird
  - name: org.libreoffice.LibreOffice
  - name: org.gimp.GIMP
  - name: org.inkscape.Inkscape
  - name: org.geany.Geany
  - name: org.gnome.TextEditor

apt_packages_present:
  - name: python-is-python3
  - name: python3-psutil
  - name: gnupg
  - name: software-properties-common
  - name: libcanberra-gtk-module
  - name: curl
  - name: flatpak

  - name: seafile-gui
    key: https://linux-clients.seafile.com/seafile.asc
    repo_url: deb [arch=amd64 signed-by=/etc/apt/keyrings/seafile] https://linux-clients.seafile.com/seafile-deb/{{ ansible_distribution_release }}/ stable main
    repo_filename: seafile
  - name: code
    key: https://packages.microsoft.com/keys/microsoft.asc
    repo_url: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft] https://packages.microsoft.com/repos/code stable main
    repo_filename: microsoft
  - name: terraform
    key: https://apt.releases.hashicorp.com/gpg
    repo_url: deb [signed-by=/etc/apt/keyrings/hashicorp] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    repo_filename: hashicorp
  - name: teamviewer
    key: https://linux.teamviewer.com/pubkey/currentkey.asc
    repo_url: deb [signed-by=/etc/apt/keyrings/teamviewer] https://linux.teamviewer.com/deb stable main
    repo_filename: teamviewer

apt_deb_present:
  - name: task
    deb_path: https://github.com/go-task/task/releases/latest/download/task_linux_amd64.deb

apt_packages_absent:
  - name: libreoffice-common
  - name: libreoffice-core
  - name: libreoffice-gnome
  - name: libreoffice-gtk3
  - name: libreoffice-help-common
  - name: libreoffice-help-en-us
  - name: libreoffice-style-colibre
  - name: libreoffice-style-elemtary

  - name: evolution
  - name: evolution-exchange
  - name: evolution-plugins
  - name: evolution-common
  - name: evolution-webcal

  - name: firefox-esr
  - name: gnome-text-editor
  - name: gedit
  - name: yelp
  - name: gnome-games
  - name: transmission-gtk
  - name: gnome-maps
  - name: malcontent