apt_packages_present:
  - name: python-is-python3
  - name: python3-psutil
  - name: flatpak

  - name: code
    key: https://packages.microsoft.com/keys/microsoft.asc
    repo_url: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main
    repo_filename: vscode

apt_packages_absent:
  - name: libreoffice-common
  - name: libreoffice-core
  - name: libreoffice-gnome
  - name: libreoffice-gtk3
  - name: libreoffice-help-common
  - name: libreoffice-help-en-us
  - name: libreoffice-style-colibre
  - name: libreoffice-style-elemtary

  - name: evolution
  - name: evolution-exchange
  - name: evolution-plugins
  - name: evolution-common
  - name: evolution-webcal

  - name: firefox-esr
  - name: gnome-text-editor
  - name: gedit
  - name: yelp
  - name: gnome-games
  - name: transmission-gtk
  - name: gnome-maps
  - name: malcontent

  - name: sublime-text
    key: https://download.sublimetext.com/sublimehq-pub.gpg
    repo_url: deb https://download.sublimetext.com/ apt/stable/
    repo_filename: sublime-text

flathub_packages_present:
  - name: ca.desrt.dconf-editor
  - name: com.google.Chrome
  - name: org.mozilla.firefox
  - name: org.mozilla.Thunderbird
  - name: org.libreoffice.LibreOffice
  - name: org.gimp.GIMP
  - name: org.inkscape.Inkscape
  - name: org.geany.Geany

flathub_packages_absent:
  - name: com.visualstudio.code
  - name: org.kde.kwrite
