---

- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories
      become: true
      apt: update_cache=yes

  vars:
    apt_package_req:
      - name: sublime-text
        key: https://download.sublimetext.com/sublimehq-pub.gpg
        repo_url: deb https://download.sublimetext.com/ apt/stable/
      - name: code
        key: https://packages.microsoft.com/keys/microsoft.asc
        repo_url: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main

  tasks:
    - name: Install python packages for dedicated enviroment
      ansible.builtin.apt:
        name:
          - python-is-python3
          - python3-psutil
          - xz-utils
        state: present

    - name: Include tasks/remove.yml in play
      ansible.builtin.include_tasks:
        file: tasks/remove.yml

    - name: Include tasks/packages.yml in play
      ansible.builtin.include_tasks:
        file: tasks/packages.yml

    - name: Include tasks/config.yml in play
      ansible.builtin.include_tasks:
        file: tasks/config.yml

    - name: Include tasks/gnome.yml in play
      ansible.builtin.include_tasks:
        file: tasks/gnome.yml
