---

- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories
      become: true
      apt: update_cache=yes

  tasks:

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: user

    - name: Install python-is-python3
      ansible.builtin.apt:
        name:
          - python-is-python3
          - python3-psutil
        state: present


    - name: Include tasks/remove.yml in play
      ansible.builtin.include_tasks:
        file: tasks/remove.yml

    - name: Include tasks/packages.yml in play
      ansible.builtin.include_tasks:
        file: tasks/packages.yml

    - name: Include tasks/config.yml in play
      ansible.builtin.include_tasks:
        file: tasks/config.yml
