---

- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories
      become: true
      apt: update_cache=yes

  vars_prompt:
    - name: username
      prompt: What is your linux username?
      private: false
  
  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/gnome.yml
