---

- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes

  vars:
    username: ''

  tasks:
    - include: tasks/packages.yml
    - include: tasks/gnome.yml
