---

- name: Set Panel Date Format
  become_user: "{{ user }}"
  community.general.dconf: key="/org/gnome/shell/extensions/panel-date-format/format" value="'%H:%M   |   %A  %d.%m.%Y'"

- name: Set GNOME wallpaper
  become_user: "{{ user }}"
  community.general.dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/{{ user }}/.wallpaper.jpg'"

- name: Set lock screen background
  become_user: "{{ user }}"
  community.general.dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///home/{{ user }}/.lockscreen.jpg'"

- name: install gnome-extensions-cli
  community.general.pipx:
    name: gnome-extensions-cli
    state: present

- name: Execute script to set shortcut with gsetting
  become_user: "{{ user }}"
  ansible.builtin.shell: ./roles/linux-workstation/files/gnome-setting.sh

###

# https://extensions.gnome.org/extension/1462/panel-date-format/
# https://extensions.gnome.org/extension/1160/dash-to-panel/



# - name: Install Shell Extenions
#   ansible.builtin.command:
#     shell: gext install 1462 1160
