---

tasks:
  - name: Install python packages for dedicated enviroment
    ansible.builtin.apt:
      name:
        - python-is-python3
        - python3-psutil
        - xz-utils
      state: present

###

- name: Install flatpak apt packages
  ansible.builtin.apt:
    name:
      - flatpak
    state: present

###

- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  community.general.flatpak:
    name:
      - ca.desrt.dconf-editor
      - com.google.Chrome
      - org.mozilla.firefox
      - org.mozilla.Thunderbird
      - org.libreoffice.LibreOffice
      - org.kde.kwrite
      - org.gimp.GIMP
      - org.inkscape.Inkscape
    state: present
    remote: flathub

- name: Install flatpak apps
  community.general.flatpak:
    name:
      - com.visualstudio.code
    state: absent

- name: write the keys into /etc/apt/keyrings/
  ansible.builtin.get_url:
    url: "{{ item.key }}"
    dest: "/etc/apt/keyrings/"
  loop: "{{ apt_packages }}"
  when: item.key != ""

- name: Add apt repository for the package
  apt_repository:
    repo: "{{ item.repo_url }}"
    state: present
  loop: "{{ apt_packages }}"
  when: item.repo_url != ""

- name: Install apt packages
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: true
  loop: "{{ apt_packages }}"
  when: item.name != ""


- name: Download VMware Workstation Install binary, there is no flatpack or deb/apt release
  ansible.builtin.get_url:
    url: https://www.vmware.com/go/getworkstation-linux
    dest: /usr/local/sbin/
    mode: -rwxr-xr-x