---


- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  community.general.flatpak:
    name:
      - ca.desrt.dconf-editor
      - com.google.Chrome
      - org.mozilla.firefox
      - org.mozilla.Thunderbird
      - org.libreoffice.LibreOffice
      - org.gimp.GIMP
      - org.inkscape.Inkscape
    state: present
    remote: flathub

- name: remove unoffical vscode flatpack
  community.general.flatpak:
    name:
      - com.visualstudio.code
      - org.kde.kwrite
    state: absent

# Add apt package logic
- name: write the keys into /etc/apt/keyrings/
  ansible.builtin.get_url:
    url: "{{ item.key }}"
    dest: "/etc/apt/keyrings/"
  loop: "{{ apt_packages_present }}"
  when: item.key is defined and != ""

- name: Add apt repository for the package
  apt_repository:
    repo: "{{ item.repo_url }}"
    state: present
  loop: "{{ apt_packages_present }}"
  when: item.repo_url is defined and != ""

- name: Install apt packages
  apt:
    name: "{{ item.name }}"
    state: present
    update_cache: true
  loop: "{{ apt_packages_present }}"
  when: item.name is defined and != ""

# Remove apt package logic
- name: Remove apt packages
  apt:
    name: "{{ item.name }}"
    state: absent
    update_cache: true
  loop: "{{ apt_packages_absent }}"
  when: item.name is defined and != ""

- name: Remove apt repository for the package
  apt_repository:
    repo: "{{ item.repo_url }}"
    state: present
  loop: "{{ apt_packages_absent }}"
  when: item.repo_url is defined and != ""


- name: Download VMware Workstation Install binary, there is no flatpack or deb/apt release
  ansible.builtin.get_url:
    url: https://www.vmware.com/go/getworkstation-linux
    dest: /usr/local/sbin/
    mode: -rwxr-xr-x