---

- name: Remove libre office apt package
  ansible.builtin.apt:
    name:
      - libreoffice-common
      - libreoffice-core
      - libreoffice-gnome
      - libreoffice-gtk3
      - libreoffice-help-common
      - libreoffice-help-en-us
      - libreoffice-style-colibre
      - libreoffice-style-elemtary
    state: absent

- name: Remove evolution
  ansible.builtin.apt:
    name:
      - evolution
      - evolution-exchange
      - evolution-plugins
      - evolution-common
      - evolution-webcal
    state: absent

- name: Remove some gnome apt packages
  ansible.builtin.apt:
    name:
      - firefox-esr
      - gnome-text-editor
      - gedit
      - yelp
      - gnome-games
      - transmission-gtk
      - gnome-maps
      - malcontent
    state: absent
