---

- name: Install flatpak packages
  ansible.builtin.apt:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
    state: present

###

- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  community.general.flatpak:
    name:
      - ca.desrt.dconf-editor
      - com.google.Chrome
      - org.mozilla.firefox
      - org.mozilla.Thunderbird
      - org.libreoffice.LibreOffice
      - org.kde.kwrite
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - com.visualstudio.code
    state: present
    remote: flathub

###

- name: Install Teamviewer .deb package from the internet
  ansible.builtin.apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
