---

###

- name: Install flatpak apt packages
  ansible.builtin.apt:
    name:
      - flatpak
    state: present

###

- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  community.general.flatpak:
    name:
      - ca.desrt.dconf-editor
      - com.google.Chrome
      - org.mozilla.firefox
      - org.mozilla.Thunderbird
      - org.libreoffice.LibreOffice
      - org.kde.kwrite
      - org.gimp.GIMP
      - org.inkscape.Inkscape
    state: present
    remote: flathub

### 

vars:
  apt_package_req:
    - name: sublime-text
      key: https://download.sublimetext.com/sublimehq-pub.gpg
      repo_url: deb https://download.sublimetext.com/ apt/stable/
    - name: code
      key: https://packages.microsoft.com/keys/microsoft.asc
      repo_url: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main

tasks:
  - name: somerepo | no apt key
    ansible.builtin.get_url:
      url: "{{ item.key }}"
      dest: "/etc/apt/keyrings/{{ item.name }}.asc"
    loop: "{{ apt_package_req }}"

  # - name: Add apt key for the package repositories
  #   apt_key:
  #     url: "{{ item.key }}"
  #     state: present
  #   loop: "{{ apt_package_req }}"

  - name: Add apt repository for the package
    apt_repository:
      repo: "{{ item.repo_url }}"
      state: present
    loop: "{{ apt_package_req }}"

  - name: Install apt packages
    apt:
      name: "{{ item.name }}"
      state: present
      update_cache: true
    loop: "{{ apt_package_req }}"

### 

- name: Install .deb packages from the internet without official flatpack releases
  ansible.builtin.apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb

- name: Download VMware Workstation Install binary, there is no flatpack or deb/apt release
  ansible.builtin.get_url:
    url: https://www.vmware.com/go/getworkstation-linux
    dest: ~/Downloads/VMware-Workstation-Install/
    mode: -rwxr-xr-x