---

###

- name: Remove libre office apt package
  ansible.builtin.apt:
    name:
      - libreoffice-common
      - libreoffice-core
      - libreoffice-gnome
      - libreoffice-gtk3
      - libreoffice-help-common
      - libreoffice-help-en-us
      - libreoffice-style-colibre
      - libreoffice-style-elemtary
    state: absent

- name: Remove evolution
  ansible.builtin.apt:
    name:
      - evolution
      - evolution-exchange
      - evolution-plugins
      - evolution-common
      - evolution-webcal
    state: absent
    
- name: Remove some gnome apt packages
  ansible.builtin.apt:
    name:
      - firefox-esr
      - gnome-text-editor
      - gedit
      - yelp
      - gnome-games
      - transmission-gtk
      - gnome-maps
      - malcontent
    state: absent
    
###
- name: Install python-is-python3
  ansible.builtin.apt:
    name:
      - python-is-python3
      - python3-psutil
    state: present

- name: Install flatpak packages
  ansible.builtin.apt:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
    state: present

- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  community.general.flatpak:
    name:
      - com.google.Chrome
      - org.mozilla.firefox
      - org.mozilla.Thunderbird
      - org.libreoffice.LibreOffice
      - org.kde.kwrite
      - org.gimp.GIMP
      - org.inkscape.Inkscape
    state: present
    remote: flathub
