---

###

- name: Install flatpak apt packages
  ansible.builtin.apt:
    name:
      - flatpak
    state: present

###

- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  community.general.flatpak:
    name:
      - ca.desrt.dconf-editor
      - com.google.Chrome
      - org.mozilla.firefox
      - org.mozilla.Thunderbird
      - org.libreoffice.LibreOffice
      - org.kde.kwrite
      - org.gimp.GIMP
      - org.inkscape.Inkscape
    state: present
    remote: flathub

###

- name: Install .deb packages from the internet without official flatpack releases
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop:
    - https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
    - https://code.visualstudio.com/docs/?dv=linux64_deb
    - https://www.sublimetext.com/download_thanks?target=x64-deb
  clean: yes
  update_cache: yes


- name: Download VMware Workstation Install binary, there is no flatpack or deb/apt release
  ansible.builtin.get_url:
    url: https://www.vmware.com/go/getworkstation-linux
    dest: ~/Downloads/VMware-Workstation-Install/
    mode: -rwxr-xr-x

# https://www.vmware.com/go/getworkstation-linux

###

# - name: import the sublime apt key
#   apt_key:
#     url: https://download.sublimetext.com/sublimehq-pub.gpg
#     state: present
#   become: true

# - name: install sublime deb repository
#   apt_repository:
#     repo: deb https://download.sublimetext.com/ apt/stable/
#     state: present
#   become: true

# - name: Install sublime apt package
#   ansible.builtin.apt:
#     name:
#       - sublime-text
#     state: present
#     update_cache: true
